language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false
script:
  - cargo build --verbose --no-default-features
  - cargo test --verbose --no-default-features
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc
after_success: curl https://raw.githubusercontent.com/Stebalien/doc/master/push_docs.sh | sh
